version: '3'
services:
  embyboss:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: embyboss
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config.json:/app/config.json
      - ./log:/app/log
